// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDzbjyZIUk5GlkdpGCi01PthlUTmmlCaoI',
    appId: '1:526977636032:web:213a6fe8e733225e7a7f25',
    messagingSenderId: '526977636032',
    projectId: 'my-ecommerce-app-25',
    authDomain: 'my-ecommerce-app-25.firebaseapp.com',
    storageBucket: 'my-ecommerce-app-25.firebasestorage.app',
    measurementId: 'G-8PJ4FTNW6X',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDalyNvs6-pj7YtHJcpIgN84jl6_egIC0w',
    appId: '1:67129227242:android:26b90ee3dffe27177a6493',
    messagingSenderId: '67129227242',
    projectId: 'my-ecommerce-project-25',
    storageBucket: 'my-ecommerce-project-25.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAz2DexCTLpuYaaL-pw1OVTI5TvjACnpVM',
    appId: '1:67129227242:ios:41968fc6bdcb51607a6493',
    messagingSenderId: '67129227242',
    projectId: 'my-ecommerce-project-25',
    storageBucket: 'my-ecommerce-project-25.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplicationEcommerce',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBryJYbYdog_RYByiYPNo7IM5GqiRvawtE',
    appId: '1:526977636032:ios:8a180e8293c649c27a7f25',
    messagingSenderId: '526977636032',
    projectId: 'my-ecommerce-app-25',
    storageBucket: 'my-ecommerce-app-25.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplicationEcommerce',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDzbjyZIUk5GlkdpGCi01PthlUTmmlCaoI',
    appId: '1:526977636032:web:4abd22485fc1d1d57a7f25',
    messagingSenderId: '526977636032',
    projectId: 'my-ecommerce-app-25',
    authDomain: 'my-ecommerce-app-25.firebaseapp.com',
    storageBucket: 'my-ecommerce-app-25.firebasestorage.app',
    measurementId: 'G-XRTXLEQE84',
  );

}